l = input()
p = l.split()
A = float(p[0])
B = float(p[1])
C = float(p[2])
print("TRIANGULO: %.3f" % float((A * C) / 2))
print("CIRCULO: %.3f" % float(3.14159 * (C * C)))
print("TRAPEZIO: %.3f" % float(((A + B) * C) / 2))
print("QUADRADO: %.3f" % float(B * B))
print("RETANGULO: %.3f" % float(A * B))
